musicsearch.settings:
  type: config_object
  label: 'Music search settings'
  mapping:
    spotify_client_id:
      type: string
      label: 'Spotify Client ID'
    spotify_client_secret:
      type: string
      label: 'Spotify Client Secret'
    discogs_token:
      type: string
      label: 'Discogs personal access token'
